
name: .NET

on: [pull_request]

jobs:
  pull-validate:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v2.0.0
    - name: Restaurar dependencias
      run: dotnet restore ./Funcionario-API.sln
    - name: Compilacao
      run: dotnet build ./Funcionario-API.sln
    - name: Testes
      run: dotnet test ./Funcionario-API.sln

